--local cmp = require'cmp'
--cmp.setup({
  --snippet = {
      --expand = function(args)
          --vim.fn['vsnip#anonymous'](args.body)
      --end,
  --},
  --mapping = {
    --['<C-d>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    --['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    --['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
    --['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
    --['<C-e>'] = cmp.mapping({
      --i = cmp.mapping.abort(),
      --c = cmp.mapping.close(),
    --}),
    --['<CR>'] = cmp.mapping.confirm({ select = true }),
    --['<C-n>'] = cmp.mapping(function(fallback)
      --if cmp.visible() then
        --cmp.select_next_item()
      --else
        --fallback()
      --end
    --end, {"i", "s"}),
    --['<C-p>'] = cmp.mapping(function(fallback)
      --if cmp.visible() then
        --cmp.select_prev_item()
      --else
        --fallback()
      --end
    --end, {"i", "s"}),
  --},
  --sources = cmp.config.sources({
    --{ name = 'nvim_lsp' },
    --{ name = 'vsnip' }, -- For vsnip users.
    ---- { name = 'luasnip' }, -- For luasnip users.
    ---- { name = 'ultisnips' }, -- For ultisnips users.
    ---- { name = 'snippy' }, -- For snippy users.
  --}, {
    ----{ name = 'buffer' },
  --}, {
    --{ name = 'path' }
  --}),
  --formatting = {
    --format = function(entry, vim_item)
      --vim_item.menu = ({
        --nvim_lsp = "[LSP]",
        --buffer = "[Buffer]"
      --})[entry.source.name]
      --return vim_item
    --end
  --}
--})


---- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
--cmp.setup.cmdline('/', {
  --mapping = cmp.mapping.preset.cmdline(),
  --sources = cmp.config.sources({{name = 'path'}}, {{name = 'buffer'}})
--})
